window.esdocSearchIndex = [
  [
    "microwork/src/plugins/hardwarestat.js~hardwarestat",
    "variable/index.html#static-variable-HardwareStat",
    "<span>HardwareStat</span> <span class=\"search-result-import-path\">microwork/src/plugins/hardwarestat.js</span>",
    "variable"
  ],
  [
    "microwork/src/plugins/healthcheck.js~healthcheck",
    "variable/index.html#static-variable-HealthCheck",
    "<span>HealthCheck</span> <span class=\"search-result-import-path\">microwork/src/plugins/healthcheck.js</span>",
    "variable"
  ],
  [
    "microwork/src/microwork.js~microwork",
    "class/src/microwork.js~Microwork.html",
    "<span>Microwork</span> <span class=\"search-result-import-path\">microwork/src/microwork.js</span>",
    "class"
  ],
  [
    "microwork/src/plugins/substats.js~subscriberstats",
    "variable/index.html#static-variable-SubscriberStats",
    "<span>SubscriberStats</span> <span class=\"search-result-import-path\">microwork/src/plugins/substats.js</span>",
    "variable"
  ],
  [
    "microwork/src/sleep.js~sleep",
    "variable/index.html#static-variable-sleep",
    "<span>sleep</span> <span class=\"search-result-import-path\">microwork/src/sleep.js</span>",
    "variable"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/logger.js",
    "file/src/logger.js.html",
    "src/logger.js",
    "file"
  ],
  [
    "src/microwork.js",
    "file/src/microwork.js.html",
    "src/microwork.js",
    "file"
  ],
  [
    "src/microwork.js~microwork#constructor",
    "class/src/microwork.js~Microwork.html#instance-constructor-constructor",
    "src/microwork.js~Microwork#constructor",
    "method"
  ],
  [
    "src/microwork.js~microwork#exchange",
    "class/src/microwork.js~Microwork.html#instance-member-exchange",
    "src/microwork.js~Microwork#exchange",
    "member"
  ],
  [
    "src/microwork.js~microwork#host",
    "class/src/microwork.js~Microwork.html#instance-member-host",
    "src/microwork.js~Microwork#host",
    "member"
  ],
  [
    "src/microwork.js~microwork#id",
    "class/src/microwork.js~Microwork.html#instance-member-id",
    "src/microwork.js~Microwork#id",
    "member"
  ],
  [
    "src/microwork.js~microwork#reconnecttimeout",
    "class/src/microwork.js~Microwork.html#instance-member-reconnectTimeout",
    "src/microwork.js~Microwork#reconnectTimeout",
    "member"
  ],
  [
    "src/microwork.js~microwork#registerplugin",
    "class/src/microwork.js~Microwork.html#instance-method-registerPlugin",
    "src/microwork.js~Microwork#registerPlugin",
    "method"
  ],
  [
    "src/microwork.js~microwork#routehandlers",
    "class/src/microwork.js~Microwork.html#instance-member-routeHandlers",
    "src/microwork.js~Microwork#routeHandlers",
    "member"
  ],
  [
    "src/microwork.js~microwork#send",
    "class/src/microwork.js~Microwork.html#instance-method-send",
    "src/microwork.js~Microwork#send",
    "method"
  ],
  [
    "src/microwork.js~microwork#stop",
    "class/src/microwork.js~Microwork.html#instance-method-stop",
    "src/microwork.js~Microwork#stop",
    "method"
  ],
  [
    "src/microwork.js~microwork#subscribe",
    "class/src/microwork.js~Microwork.html#instance-method-subscribe",
    "src/microwork.js~Microwork#subscribe",
    "method"
  ],
  [
    "src/microwork.js~microwork#tryreconnect",
    "class/src/microwork.js~Microwork.html#instance-method-tryReconnect",
    "src/microwork.js~Microwork#tryReconnect",
    "method"
  ],
  [
    "src/microwork.js~microwork#unsubscribe",
    "class/src/microwork.js~Microwork.html#instance-method-unsubscribe",
    "src/microwork.js~Microwork#unsubscribe",
    "method"
  ],
  [
    "src/plugins/hardwarestat.js",
    "file/src/plugins/hardwarestat.js.html",
    "src/plugins/hardwarestat.js",
    "file"
  ],
  [
    "src/plugins/healthcheck.js",
    "file/src/plugins/healthcheck.js.html",
    "src/plugins/healthcheck.js",
    "file"
  ],
  [
    "src/plugins/substats.js",
    "file/src/plugins/substats.js.html",
    "src/plugins/substats.js",
    "file"
  ],
  [
    "src/sleep.js",
    "file/src/sleep.js.html",
    "src/sleep.js",
    "file"
  ]
]